WITH totals AS (
    SELECT * FROM {{ ref('stg_senate_totals') }}
)

SELECT
    row_number() OVER (ORDER BY SUM(VOTES) DESC) AS RANK
    , CANDIDATE_NAME
    , SUM(VOTES) AS TOTAL_VOTES
    , ROUND(SUM(VOTES) * 100.0 / SUM(SUM(VOTES)) OVER (), 2) AS VOTE_PERCENTAGE
    , CASE
        WHEN row_number() OVER (ORDER BY SUM(VOTES) DESC) <= 12 THEN TRUE
        ELSE FALSE
      END AS WINNER
FROM totals
GROUP BY CANDIDATE_NAME
ORDER BY TOTAL_VOTES DESC
